nicknames = (
    ('Aleksey', 'Alexey'),
    ('Abigail', 'Abby'),
    ('Abdelfettah', 'Abdelfattah'),
    ('Alexander', 'Alex'),
    ('SangiovanniVincent', 'SangiovanniVincentelli'),
    ('Allan', 'Allen', 'Alan', 'Al'),
    ('Allison', 'Alison', 'Ali', 'Aly', 'Allie'),
    ('Andre', u'Andr\00e9'),
    ('Andrew', 'Andy', 'Drew'),
    ('Anatoly', 'Anatolij'),
    ('Antonio', 'Anthony', 'Tony', 'Anton'),
    ('Barbara', 'Barb'),
    ('Benjamin', 'Ben'),
    ('Bernard', 'Bernie'),
    ('Babaouglu', 'BabaoOlu'),
    ('Calvin', 'Cal'),
    ('Catherine', 'Cathy', 'Cath'),
    ('Charles', 'Chas', 'Chuck', 'Chucky', 'Charlie'),
    ('Christine', 'Christina', 'Chris'),
    ('Christopher', 'Chris'),
    ('Constantinos', 'Costas'),
    ('Daniel', 'Dan', 'Danny'),
    ('David', 'Dave'),
    ('Deborah', 'Debbie'),
    ('Dennis', 'Denny'),
    ('Des', 'Desmond'),
    ('Dias', 'Das'),
    ('Donald', 'Don', 'Donny'),
    ('Douglas', 'Doug'),
    ('Delft', 'Vandelft', 'Van'),
    ('Edward', 'Ed', 'Eddie', 'Eddy'),
    ('Elizabeth', 'Liz', 'Lizbet', 'Lizbeth', 'Beth', 'Lizzie'),
    ('Francis', 'Frank', 'Frankie'),
    ('Fredrick', 'Frederick', 'Fred', 'Freddy'),
    ('FemandezRedondo', 'FemaindezRedondo', 'FernandezRedondo', 'Fernaindez-Redondo'),
    ('Fons', 'Alphons', 'Alfons'),
    ('Gerard', 'Gerry', 'Jerry'),
    ('Gert', 'Gerrit'),
    ('Gregory', 'Greg'),
    ('Georgios', 'Georges'),
    ('Harris', 'Harry', 'Harrison'),
    ('Henry', 'Hank'),
    ('Henry', 'Henri'),
    ('Hendrik', 'henk'),
    ('Herbert', 'Herb'),
    ('Howard', 'Howie'),
    ('Hossein', 'Hosein'),
    ('James', 'Jim', 'Jimmy'),
    ('Jerome', 'Jerry'),
    ('John', 'Jon', 'Johnny', 'Jack'),
    ('Joseph', 'Joe'),
    ('Judith', 'Judy'),
    ('Johnathan', 'John'),
    ('Jonathan', 'Jon'),
    ('Katherine', 'Kathy', 'Katie'),
    ('Catherine', 'Cathy', 'Kathy'),
    ('Kathleen', 'Kathy'),
    ('Kenneth', 'Ken', 'Kenny'),
    ('Lawrence', 'Laurence', 'Larry'),
    ('Lewis', 'Louis', 'Lou'),
    ('Matthew', 'Matt'),
    ('Margaret', 'Marge', 'Margie', 'Maggie', 'Meg'),
    ('Martin', 'Marty'),
    ('Maryan',  'Maria'),
    ('Melvin', 'Melvyn' ,'Mel'),
    ('Mervyn', 'Merv'),
    ('Michael', 'Mike', 'Michel', 'Michal'),
    ('Mitchell', 'Mitch'),
    ('Mohamad', 'Mohammad', 'Mohamed', 'Mohammed'),
    ('Nicholas', 'Nick'),
    ('Nasser', 'Naser'),
    ('Natalia', 'Natalya'),
    ('Nouredine', 'Nordine'),
    ('Patricia', 'Pat', 'Patty', 'Pati'),
    ('Patrick', 'Pat'),
    ('Patricia', 'Patrice'),
    ('Peter', 'Pete'),
    ('Peter', 'Petar'),
    ('Peter', 'Petra'),
    ('Philip', 'Phillip', 'Phil'),
    ('Panagiotis', 'Panos'),
    ('Randall', 'Randy'),
    ('Richard', 'Rick', 'Dick', 'Rich', 'Ricky'),
    ('Robert', 'Rob', 'Robby', 'Bobby', 'Bob'),
    ('Renaud', 'Renauld'),
    ('ruizcort', 'ruizcortes'),
    ('Samual', 'Sam'),
    ('Steven', 'Stephen', 'Steve'),
    ('Stephan', 'Stefan'),
    ('Stephanie', 'Steph'),
    ('Stewart', 'Stuart', 'Stu'),
    ('Theodore', 'Ted', 'Teddy'),
    ('Terrance', 'Terry'),
    ('Terry', 'Taras'),
    ('Thomas', 'Tom', 'Thom', 'Tommy'),
    ('Uur', 'Ugur'),
    ('Vernon', 'Vern'),
    ('William', 'Bill', 'Billy', 'Will', 'Willy'),
    ('Willis', 'Will'),
    ('Yanb', 'Yan'),
    ('Yossef', 'Yossi'),
    ('Yuri', 'Yuriy', 'Yurii', 'Yury', 'Yu'),
    ('Aaron', 'Ron', 'Ronnie', 'Ronny'),
    ('Abel', 'Abe', 'Abie'),
    ('Abigail', 'Abbie', 'Abby', 'Gail', 'Nabby'),
    ('Abner', 'Ab', 'Abbie'),
    ('Abraham', 'Abe', 'Abie', 'Bram'),
    ('Ada', 'Adie'),
    ('Adaline', 'Addie', 'Aline', 'Dell', 'Della'),
    ('Adam', 'Ad', 'Addie', 'Addy', 'Ade'),
    ('Adela', 'Addie', 'Dell', 'Della'),
    ('Adelaide', 'Addie', 'Adela', 'Dell', 'Della', 'Heidi'),
    ('Adele', 'Addie', 'Dell', 'Della'),
    ('Adelina', 'Addie', 'Aline', 'Dell', 'Della'),
    ('Adeline', 'Addie', 'Aline', 'Dell', 'Della'),
    ('Adelle', 'Addie', 'Dell', 'Della'),
    ('Adrian', 'Ade'),
    ('Adriana', 'Adie'),
    ('Adrienne', 'Adie'),
    ('Agatha', 'Aggie'),
    ('Agnes', 'Aggie', 'Ness', 'Nessie'),
    ('Aileen', 'Allie', 'Lena'),
    ('Alan', 'Al'),
    ('Alastair', 'Al'),
    ('Alaster', 'Al'),
    ('Albert', 'Al', 'Bert', 'Bertie'),
    ('Alberta', 'Allie', 'Bertie'),
    ('Alene', 'Allie', 'Lena'),
    ('Alexander', 'Al', 'Alex', 'Alec', 'Aleck', 'Lex', 'Sandy', 'Sander'),
    ('Alexandra', 'Alex', 'Alix', 'Alexa', 'Alla', 'Allie', 'Ali', 'Lexy', 'Sandra', 'Sandy'),
    ('Alexandria', 'Alex', 'Alix', 'Alexa', 'Alla', 'Allie', 'Ali', 'Lexy', 'Sandra', 'Sandy'),
    ('Alexis', 'Alex'),
    ('Alfred', 'Al', 'Alf', 'Alfie', 'Fred', 'Freddie', 'Freddy'),
    ('Alfreda', 'Alfie', 'Alfy', 'Frieda', 'Freda', 'Freddie', 'Freddy'),
    ('Algernon', 'Algie', 'Algy', 'Alger'),
    ('Alice', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Alicia', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Alisa', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Alison', 'Allie', 'Ally', 'Ali'),
    ('Alissa', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Alistair', 'Al'),
    ('Alister', 'Al'),
    ('Allan', 'Al'),
    ('Allen', 'Al'),
    ('Allison', 'Allie', 'Ally', 'Ali'),
    ('Allister', 'Al'),
    ('Allyson', 'Allie', 'Ally', 'Ali'),
    ('Alonso', 'Al', 'Lon', 'Lonnie', 'Lonny'),
    ('Alonzo', 'Al', 'Lon', 'Lonnie', 'Lonny'),
    ('Althea', 'Thea'),
    ('Alvin', 'Al', 'Vin', 'Vinny', 'Win'),
    ('Alwin', 'Al', 'Vin', 'Vinny', 'Win'),
    ('Alwyn', 'Al', 'Vin', 'Vinny', 'Win'),
    ('Alyce', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Alyson', 'Allie', 'Ally', 'Ali'),
    ('Alyssa', 'Allie', 'Ally', 'Ali', 'Elsie', 'Lisa'),
    ('Amabel', 'Mabel', 'Mab', 'Mabs', 'Mabbie'),
    ('Amanda', 'Mandy'),
    ('Ambrose', 'Ambie', 'Brose'),
    ('Amelia', 'Amy', 'Millie', 'Milly'),
    ('Anabel', 'Ann', 'Anna', 'Bel', 'Belle', 'Bell'),
    ('Anastasia', 'Ana', 'Stacy', 'Stacey'),
    ('Andre', 'Andy'),
    ('Andrea', 'Andy'),
    ('Andreas', 'Andy'),
    ('Andres', 'Andy'),
    ('Andrew', 'Andy', 'Drew'),
    ('Angel', 'Angie'),
    ('Angela', 'Angie'),
    ('Angelica', 'Angie'),
    ('Angelina', 'Angie'),
    ('Angeline', 'Angie'),
    ('Anita', 'Ana', 'Nita'),
    ('Ann', 'Ann', 'Annie', 'Nancy', 'Nancie', 'Nance', 'Nan', 'Nana', 'Nanny', 'Nanette', 'Nannette', 'Nina'),
    ('Anna', 'Ann', 'Annie', 'Nancy', 'Nancie', 'Nance', 'Nan', 'Nana', 'Nanny', 'Nanette', 'Nannette', 'Nina'),
    ('Annabel', 'Ann', 'Anna', 'Bel', 'Belle', 'Bell'),
    ('Annabelle', 'Ann', 'Anna', 'Bel', 'Belle', 'Bell'),
    ('Anne', 'Ann', 'Annie', 'Nancy', 'Nancie', 'Nance', 'Nan', 'Nana', 'Nanny', 'Nanette', 'Nannette', 'Nina'),
    ('Annetta', 'Annie', 'Netta', 'Nettie', 'Netty'),
    ('Annette', 'Annie', 'Netta', 'Nettie', 'Netty'),
    ('Anthony', 'Tony'),
    ('Antoinette', 'Nettie', 'Netty', 'Net', 'Netta', 'Toni', 'Tony', 'Toy', 'Toi'),
    ('Anton', 'Tony'),
    ('Antonia', 'Toni', 'Tony', 'Tonya', 'Tonia'),
    ('Antony', 'Tony'),
    ('Arabel', 'Bel', 'Bell', 'Belle', 'Bella'),
    ('Arabella', 'Bel', 'Bell', 'Belle', 'Bella'),
    ('Arabelle', 'Bel', 'Bell', 'Belle', 'Bella'),
    ('Archibald', 'Arch', 'Archie', 'Baldie'),
    ('Arleen', 'Lena', 'Arly', 'Lynn'),
    ('Arlene', 'Lena', 'Arly', 'Lynn'),
    ('Arline', 'Lena', 'Arly', 'Lynn'),
    ('Arlyne', 'Lena', 'Arly', 'Lynn'),
    ('Arnold', 'Arnie'),
    ('Aron', 'Ron', 'Ronnie', 'Ronny'),
    ('Arthur', 'Art', 'Artie'),
    ('Ashley', 'Ash'),
    ('Audrey', 'Dee'),
    ('August', 'Augie', 'Gus', 'Gussy', 'Gust', 'Gustus'),
    ('Augusta', 'Aggy', 'Augie', 'Gussie', 'Gusty', 'Ina', 'Tina'),
    ('Augustina', 'Aggy', 'Augie', 'Gussie', 'Gusty', 'Ina', 'Tina'),
    ('Augustine', 'Augie', 'Gus', 'Gussy', 'Gust', 'Gustus'),
    ('Augustus', 'Augie', 'Gus', 'Gussy', 'Gust', 'Gustus'),
    ('Aurora', 'Rori'),
    ('Avery', 'Avy'),
    ('Baldwin', 'Baldie', 'Win'),
    ('Barbara', 'Bab', 'Babs', 'Babbie', 'Barbie', 'Babette'),
    ('Barnard', 'Bernie', 'Berney', 'Barney', 'Barnie'),
    ('Barrett', 'Barry', 'Barrie'),
    ('Bartholomew', 'Bart', 'Barty', 'Bartlett', 'Bartley', 'Bat', 'Batty'),
    ('Basil', 'Baz', 'Basie'),
    ('Beatrice', 'Bea', 'Bee', 'Beattie', 'Trixie', 'Trissie'),
    ('Beatrix', 'Bea', 'Bee', 'Beattie', 'Trixie', 'Trissie'),
    ('Belinda', 'Bel', 'Bell', 'Belle', 'Linda', 'Lindy', 'Lin', 'Lynn'),
    ('Benedict', 'Ben', 'Bennie', 'Benny'),
    ('Benjamin', 'Ben', 'Bennie', 'Benny', 'Benjy', 'Benjie'),
    ('Bennet', 'Ben', 'Bennie', 'Benny'),
    ('Bennett', 'Ben', 'Bennie', 'Benny'),
    ('Berenice', 'Bernie'),
    ('Bernard', 'Bernie', 'Berney', 'Barney', 'Barnie'),
    ('Bernice', 'Bernie'),
    ('Berta', 'Bertie'),
    ('Bertha', 'Bertie'),
    ('Beverley', 'Bev'),
    ('Beverly', 'Bev'),
    ('Bradford', 'Brad', 'Ford'),
    ('Bradley', 'Brad'),
    ('Branden', 'Brandy'),
    ('Brandon', 'Brandy'),
    ('Brenda', 'Brendie', 'Brandy'),
    ('Brenton', 'Brent'),
    ('Bridget', 'Biddie', 'Biddy', 'Bridie', 'Bridey', 'Brie', 'Bree', 'Brita'),
    ('Bridgette', 'Biddie', 'Biddy', 'Bridie', 'Bridey', 'Brie', 'Bree', 'Brita'),
    ('Brigid', 'Biddie', 'Biddy', 'Bridie', 'Bridey', 'Brie', 'Bree', 'Brita'),
    ('Brigit', 'Biddie', 'Biddy', 'Bridie', 'Bridey', 'Brie', 'Bree', 'Brita'),
    ('Britney', 'Brit', 'Britt', 'Brita', 'Brie'),
    ('Brittany', 'Brit', 'Britt', 'Brita', 'Brie'),
    ('Brittney', 'Brit', 'Britt', 'Brita', 'Brie'),
    ('Broderick', 'Brodie', 'Brody', 'Brady', 'Rick', 'Ricky'),
    ('Burton', 'Burt'),
    ('Byron', 'Ron', 'Ronnie', 'Ronny'),
    ('Caleb', 'Cal'),
    ('Calvin', 'Cal', 'Vin', 'Vinny'),
    ('Cameron', 'Cam', 'Ron', 'Ronny'),
    ('Camila', 'Cammie', 'Cammy', 'Millie'),
    ('Camile', 'Cammie', 'Cammy', 'Millie'),
    ('Camilla', 'Cammie', 'Cammy', 'Millie'),
    ('Camille', 'Cammie', 'Cammy', 'Millie'),
    ('Candace', 'Candy'),
    ('Candice', 'Candy'),
    ('Caren', 'Carrie'),
    ('Carin', 'Carrie'),
    ('Carla', 'Carlie', 'Carly'),
    ('Carline', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Carlota', 'Lotta', 'Lottie', 'Lotty'),
    ('Carlotta', 'Lotta', 'Lottie', 'Lotty'),
    ('Carlyne', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Carol', 'Carrie', 'Carry'),
    ('Carole', 'Carrie', 'Carry'),
    ('Carolina', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Caroline', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Carolyn', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Carrol', 'Carrie', 'Carry'),
    ('Carroll', 'Carrie', 'Carry'),
    ('Caryn', 'Carrie'),
    ('Caspar', 'Cas', 'Cass'),
    ('Casper', 'Cas', 'Cass'),
    ('Cassandra', 'Cass', 'Cassie', 'Cassey', 'Casey', 'Sandra', 'Sandy'),
    ('Cassius', 'Cas', 'Cass'),
    ('Catharine', 'Cat', 'Cattie', 'Catty', 'Cathie', 'Cathy', 'Cassie', 'Kit', 'Kitty', 'Kittie'),
    ('Catherine', 'Cat', 'Cattie', 'Catty', 'Cathie', 'Cathy', 'Cassie', 'Kit', 'Kitty', 'Kittie'),
    ('Catheryn', 'Cat', 'Cattie', 'Catty', 'Cathie', 'Cathy', 'Cassie', 'Kit', 'Kitty', 'Kittie'),
    ('Cathleen', 'Cat', 'Cattie', 'Catty', 'Cathie', 'Cathy', 'Cassie', 'Kit', 'Kitty', 'Kittie'),
    ('Cathryn', 'Cat', 'Cattie', 'Catty', 'Cathie', 'Cathy', 'Cassie', 'Kit', 'Kitty', 'Kittie'),
    ('Cecelia', 'Cissy', 'Sissy', 'Celia'),
    ('Cecil', 'Cis'),
    ('Cecile', 'Cissy', 'Sissy', 'Celia'),
    ('Cecilia', 'Cissy', 'Sissy', 'Celia'),
    ('Cecillia', 'Cissy', 'Sissy', 'Celia'),
    ('Cecily', 'Cissy', 'Sissy', 'Celia'),
    ('Cedric', 'Ced', 'Rick', 'Ricky'),
    ('Celena', 'Lena', 'Lina'),
    ('Celeste', 'Celie', 'Lessie'),
    ('Celestina', 'Celie', 'Lessie', 'Tina'),
    ('Celestine', 'Celie', 'Lessie', 'Tina'),
    ('Celia', 'Celie', 'Cel'),
    ('Celina', 'Lena', 'Lina'),
    ('Celine', 'Lena', 'Lina'),
    ('Charity', 'Chattie', 'Chatty', 'Cherry'),
    ('Charles', 'Charlie', 'Charley', 'Chuck', 'Chas'),
    ('Charlotte', 'Lotta', 'Lottie', 'Lotty', 'Lola', 'Lolita', 'Chattie', 'Charlie'),
    ('Cheryl', 'Cherie'),
    ('Chester', 'Chet'),
    ('Christian', 'Chris', 'Christy', 'Kit'),
    ('Christiana', 'Chris', 'Christy', 'Christie', 'Christa', 'Chrissie', 'Kit', 'Tina'),
    ('Christina', 'Chris', 'Christy', 'Christie', 'Christa', 'Chrissie', 'Kit', 'Tina'),
    ('Christine', 'Chris', 'Christy', 'Christie', 'Christa', 'Chrissie', 'Kit', 'Tina'),
    ('Christopher', 'Chris', 'Kris', 'Cris', 'Christy', 'Kit', 'Kester', 'Kristof', 'Toph', 'Topher', 'Kris', 'Kit', 'Kester'),
    ('Chrystal', 'Crys', 'Chris'),
    ('Cicely', 'Cissy', 'Sissy', 'Celia'),
    ('Clarence', 'Clare', 'Clair'),
    ('Clarice', 'Clara', 'Clare', 'Clair'),
    ('Clarissa', 'Clara', 'Clare', 'Clair'),
    ('Claudia', 'Claudie'),
    ('Clayton', 'Clay'),
    ('Clement', 'Clem'),
    ('Clementina', 'Clem', 'Clemmie', 'Tina'),
    ('Clementine', 'Clem', 'Clemmie', 'Tina'),
    ('Clifford', 'Cliff', 'Ford'),
    ('Clinton', 'Clint'),
    ('Colin', 'Cole', 'Col'),
    ('Collen', 'Cole', 'Col'),
    ('Collin', 'Cole', 'Col'),
    ('Conrad', 'Con', 'Connie', 'Conny'),
    ('Constance', 'Connie', 'Connee', 'Conny'),
    ('Cora', 'Co', 'Cori', 'Corrie', 'Corey', 'Cory'),
    ('Cordelia', 'Cordy', 'Cori', 'Delia'),
    ('Corina', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Corine', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Corinna', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Corinne', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Cornelia', 'Connie', 'Conny', 'Corny', 'Cori', 'Nell', 'Nellie'),
    ('Cornelius', 'Connie', 'Conny', 'Corny', 'Corney', 'Cory'),
    ('Corrine', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Corynne', 'Cora', 'Cori', 'Corrie', 'Cory'),
    ('Courtney', 'Court', 'Courtie'),
    ('Crystal', 'Crys', 'Chris'),
    ('Curtis', 'Curt', 'Kurt', 'Kurt', 'Curt', 'Kurt', 'Curt'),
    ('Cynthia', 'Cindy'),
    ('Cyril', 'Cy'),
    ('Cyrus', 'Cy'),
    ('Daniel', 'Dan', 'Danny'),
    ('Daniela', 'Dani', 'Danny'),
    ('Danielle', 'Dani', 'Danny'),
    ('Daphne', 'Daph', 'Daphie'),
    ('Darleen', 'Lena', 'Darla'),
    ('Darlene', 'Lena', 'Darla'),
    ('Darlyne', 'Lena', 'Darla'),
    ('Darrel', 'Darry'),
    ('Darrell', 'Darry'),
    ('Darryl', 'Darry'),
    ('Daryl', 'Darry'),
    ('David', 'Dave', 'Davie', 'Davy'),
    ('Deborah', 'Debbie', 'Debby', 'Debra'),
    ('Delia', 'Dell', 'Della'),
    ('Delores', 'Lola', 'Lolita'),
    ('Denice', 'Denny'),
    ('Denis', 'Den', 'Denny'),
    ('Denise', 'Denny'),
    ('Dennis', 'Den', 'Denny'),
    ('Derek', 'Derry', 'Rick', 'Ricky'),
    ('Derrick', 'Derry', 'Rick', 'Ricky'),
    ('Dexter', 'Dex'),
    ('Diana', 'Di'),
    ('Diane', 'Di'),
    ('Dianne', 'Di'),
    ('Dina', 'Di'),
    ('Dinah', 'Di'),
    ('Dolores', 'Lola', 'Lolita'),
    ('Dominic', 'Dom', 'Nick'),
    ('Dominica', 'Minnie', 'Nicki', 'Nikki'),
    ('Dominick', 'Dom', 'Nick'),
    ('Dominique', 'Minnie', 'Nicki', 'Nikki'),
    ('Donald', 'Don', 'Donnie', 'Donny'),
    ('Dora', 'Dorrie', 'Dori'),
    ('Doreen', 'Dorrie'),
    ('Dorene', 'Dorrie'),
    ('Doris', 'Dorrie'),
    ('Dorothea', 'Dora', 'Dorrie', 'Doll', 'Dolly', 'Dodie', 'Dot', 'Dottie', 'Dotty', 'Dee'),
    ('Dorothy', 'Dora', 'Dorrie', 'Doll', 'Dolly', 'Dodie', 'Dot', 'Dottie', 'Dotty', 'Dee'),
    ('Dorris', 'Dorrie'),
    ('Douglas', 'Doug'),
    ('Douglass', 'Doug'),
    ('Dustin', 'Dusty'),
    ('Earnest', 'Ernie'),
    ('Earnestine', 'Erna', 'Ernie', 'Tina'),
    ('Edgar', 'Ed', 'Eddie', 'Eddy', 'Ned'),
    ('Edith', 'Edie', 'Edye', 'Dee'),
    ('Edna', 'Eddie'),
    ('Edward', 'Ed', 'Eddie', 'Eddy', 'Ned', 'Ted', 'Teddy'),
    ('Edwin', 'Ed', 'Eddie', 'Eddy', 'Ned'),
    ('Edyth', 'Edie', 'Edye', 'Dee'),
    ('Edythe', 'Edie', 'Edye', 'Dee'),
    ('Eileen', 'Allie', 'Lena'),
    ('Elaine', 'Ellie', 'Elly', 'Lainie'),
    ('Elbert', 'Bert', 'Bertie'),
    ('Eleanor', 'Ella', 'Ellie', 'Elly', 'Nell', 'Nellie', 'Nelly', 'Nora', 'Lally', 'Lallie'),
    ('Elena', 'Nell', 'Nellie', 'Nelly', 'Ellie', 'Elly', 'Lena', 'Lala', 'Lally', 'Lallie'),
    ('Elenore', 'Ella', 'Ellie', 'Elly', 'Nell', 'Nellie', 'Nelly', 'Nora', 'Lally', 'Lallie'),
    ('Eleonora', 'Ella', 'Ellie', 'Elly', 'Nell', 'Nellie', 'Nelly', 'Nora', 'Lally', 'Lallie'),
    ('Eleonore', 'Ella', 'Ellie', 'Elly', 'Nell', 'Nellie', 'Nelly', 'Nora', 'Lally', 'Lallie'),
    ('Elijah', 'Eli', 'Lige'),
    ('Elinor', 'Ella', 'Ellie', 'Elly', 'Nell', 'Nellie', 'Nelly', 'Nora', 'Lally', 'Lallie'),
    ('Elisa', 'Elsie'),
    ('Elisabeth', 'Betty', 'Bettie', 'Bet', 'Bett', 'Bette', 'Betta', 'Betsy', 'Betsey', 'Betsi', 'Beth', 'Bess', 'Bessie', 'Bessy', 'Bettina', 'Elsie', 'Elisa', 'Elsa', 'Eliza', 'Ellie', 'Elly', 'Ilse', 'Liz', 'Lizzy', 'Lizzie', 'Liza', 'Lisa', 'Lise', 'Lisette', 'Lizette', 'Lisbet', 'Lizbeth', 'Libby'),
    ('Elise', 'Elsie'),
    ('Elisia', 'Elsie'),
    ('Elissa', 'Elsie'),
    ('Eliza', 'Elsie'),
    ('Elizabeth', 'Betty', 'Bettie', 'Bet', 'Bett', 'Bette', 'Betta', 'Betsy', 'Betsey', 'Betsi', 'Beth', 'Bess', 'Bessie', 'Bessy', 'Bettina', 'Elsie', 'Elisa', 'Elsa', 'Eliza', 'Ellie', 'Elly', 'Ilse', 'Liz', 'Lizzy', 'Lizzie', 'Liza', 'Lisa', 'Lise', 'Lisette', 'Lizette', 'Lisbet', 'Lizbeth', 'Libby'),
    ('Ella', 'Ellie', 'Elly', 'Nellie', 'Nelly'),
    ('Ellen', 'Nell', 'Nellie', 'Nelly', 'Ellie', 'Elly', 'Lena', 'Lala', 'Lally', 'Lallie'),
    ('Elliot', 'El'),
    ('Elliott', 'El'),
    ('Elmer', 'El'),
    ('Eloise', 'Lois'),
    ('Elsa', 'Elsie'),
    ('Elvin', 'El', 'Vin', 'Win'),
    ('Elvira', 'Elvie'),
    ('Elwin', 'El', 'Vin', 'Win'),
    ('Elwood', 'El', 'Woody'),
    ('Elwyn', 'El', 'Vin', 'Win'),
    ('Elyse', 'Elsie'),
    ('Emanuel', 'Manny', 'Mannie', 'Manny', 'Mannie', 'Manny', 'Mannie'),
    ('Emery', 'Em'),
    ('Emil', 'Em'),
    ('Emile', 'Em'),
    ('Emilia', 'Em', 'Emmy', 'Emmie', 'Millie', 'Milly'),
    ('Emily', 'Em', 'Emmy', 'Emmie', 'Millie', 'Milly'),
    ('Emma', 'Em', 'Emm', 'Emmy', 'Emmie'),
    ('Emmanuel', 'Manny', 'Mannie', 'Manny', 'Mannie', 'Manny', 'Mannie'),
    ('Emmery', 'Em'),
    ('Emory', 'Em'),
    ('Eric', 'Rick', 'Ricky'),
    ('Erica', 'Ricky', 'Rickie'),
    ('Erick', 'Rick', 'Ricky'),
    ('Ericka', 'Ricky', 'Rickie'),
    ('Erik', 'Rick', 'Ricky'),
    ('Erika', 'Ricky', 'Rickie'),
    ('Ernest', 'Ernie'),
    ('Ernestine', 'Erna', 'Ernie', 'Tina'),
    ('Ervin', 'Erv', 'Vin', 'Win'),
    ('Erwin', 'Erv', 'Vin', 'Win'),
    ('Estella', 'Essie', 'Stella'),
    ('Estelle', 'Essie', 'Stella'),
    ('Ester', 'Essie', 'Ettie', 'Etty', 'Hettie', 'Hetty'),
    ('Esther', 'Essie', 'Ettie', 'Etty', 'Hettie', 'Hetty'),
    ('Ethel', 'Eth'),
    ('Etta', 'Ettie', 'Etty'),
    ('Eugene', 'Gene'),
    ('Eugenia', 'Gene', 'Genie'),
    ('Eugenie', 'Gene', 'Genie'),
    ('Eulalia', 'Eula', 'Lally', 'Lallie'),
    ('Eunice', 'Euny', 'Eunie'),
    ('Euphemia', 'Effie', 'Effy', 'Euphie', 'Phemie'),
    ('Euphemie', 'Effie', 'Effy', 'Euphie', 'Phemie'),
    ('Eustace', 'Stacy', 'Stacey'),
    ('Eustacia', 'Stacy', 'Stacey', 'Stacia'),
    ('Eva', 'Evie'),
    ('Evangelina', 'Eve', 'Evie', 'Angie', 'Lynn'),
    ('Evangeline', 'Eve', 'Evie', 'Angie', 'Lynn'),
    ('Eve', 'Evie'),
    ('Eveleen', 'Eve', 'Evie', 'Evvie', 'Lynn'),
    ('Evelina', 'Eve', 'Evie', 'Evvie', 'Lynn'),
    ('Eveline', 'Eve', 'Evie', 'Evvie', 'Lynn'),
    ('Evelyn', 'Eve', 'Evie', 'Evvie', 'Lynn'),
    ('Evelynne', 'Eve', 'Evie', 'Evvie', 'Lynn'),
    ('Fabian', 'Fabe', 'Fab'),
    ('Faith', 'Fae', 'Fay', 'Faye'),
    ('Felice', 'Fee', 'Fel'),
    ('Felicia', 'Fee', 'Fel'),
    ('Felicity', 'Fee', 'Fel'),
    ('Ferdinand', 'Ferdie', 'Fred', 'Freddie'),
    ('Fernando', 'Ferdie', 'Fern'),
    ('Florence', 'Flo', 'Floy', 'Floss', 'Flossie', 'Flora', 'Florrie'),
    ('Floyd', 'Floy', 'Loy', 'Floy'),
    ('Frances', 'Fan', 'Fannie', 'Fanny', 'Fran', 'Frannie', 'Franny', 'Francie', 'Francy', 'France', 'Frankie', 'Franky'),
    ('Francesca', 'Fran', 'Cesca'),
    ('Francine', 'Fan', 'Fannie', 'Fanny', 'Fran', 'Frannie', 'Franny', 'Francie', 'Francy', 'France', 'Frankie', 'Franky'),
    ('Francis', 'Frank', 'Frankie', 'Franky', 'Fran'),
    ('Francisca', 'Fran', 'Cesca'),
    ('Francisco', 'Frank', 'Frankie', 'Franky', 'Fran'),
    ('Franklin', 'Frank', 'Frankie', 'Franky'),
    ('Franklyn', 'Frank', 'Frankie', 'Franky'),
    ('Frederic', 'Fred', 'Freddie', 'Freddy', 'Rick', 'Ricky'),
    ('Frederica', 'Freda', 'Freddie', 'Freddy', 'Ricky', 'Rickie'),
    ('Frederick', 'Fred', 'Freddie', 'Freddy', 'Rick', 'Ricky'),
    ('Fredericka', 'Freda', 'Freddie', 'Freddy', 'Ricky', 'Rickie'),
    ('Frederika', 'Freda', 'Freddie', 'Freddy', 'Ricky', 'Rickie'),
    ('Fredric', 'Fred', 'Freddie', 'Freddy', 'Rick', 'Ricky'),
    ('Fredrick', 'Fred', 'Freddie', 'Freddy', 'Rick', 'Ricky'),
    ('Gabriel', 'Gabe', 'Gabby'),
    ('Gabriela', 'Gabby', 'Gabi', 'Gaby'),
    ('Gabriella', 'Gabby', 'Gabi', 'Gaby'),
    ('Gabrielle', 'Gabby', 'Gabi', 'Gaby'),
    ('Garret', 'Gary', 'Garry'),
    ('Garrett', 'Gary', 'Garry'),
    ('Genevieve', 'Gene', 'Ginny', 'Jenny', 'Viv'),
    ('Geoffrey', 'Jeff', 'Jeff', 'Jeff'),
    ('George', 'Georgie', 'Geordie'),
    ('Georgina', 'Georgie', 'Gina'),
    ('Georgine', 'Georgie', 'Gina'),
    ('Gerald', 'Gerry', 'Jerry'),
    ('Geraldine', 'Gerry', 'Gerrie', 'Gerri', 'Jerry', 'Dina'),
    ('Gerard', 'Gerry', 'Jerry'),
    ('Gertrude', 'Gertie', 'Trudie', 'Trudy'),
    ('Gilbert', 'Gil', 'Bert'),
    ('Gillian', 'Jill'),
    ('Gladys', 'Glad'),
    ('Glenda', 'Glen'),
    ('Gloria', 'Glory'),
    ('Grace', 'Gracie'),
    ('Gregor', 'Greg', 'Gregg'),
    ('Gregory', 'Greg', 'Gregg'),
    ('Griffin', 'Griff'),
    ('Griffith', 'Griff'),
    ('Gwendolen', 'Gwen', 'Gwenda', 'Wendy'),
    ('Gwendolyn', 'Gwen', 'Gwenda', 'Wendy'),
    ('Hanna', 'Ann', 'Annie', 'Nana', 'Nanny'),
    ('Hannah', 'Ann', 'Annie', 'Nana', 'Nanny'),
    ('Harold', 'Hal', 'Harry'),
    ('Harriet', 'Hattie', 'Hatty'),
    ('Harvey', 'Harve'),
    ('Heather', 'Hettie', 'Hetty'),
    ('Helaine', 'Ellie', 'Elly', 'Lainie'),
    ('Helen', 'Nell', 'Nellie', 'Nelly', 'Ellie', 'Elly', 'Lena', 'Lala', 'Lally', 'Lallie'),
    ('Helena', 'Nell', 'Nellie', 'Nelly', 'Ellie', 'Elly', 'Lena', 'Lala', 'Lally', 'Lallie'),
    ('Heloise', 'Lois'),
    ('Henrietta', 'Etta', 'Ettie', 'Etty', 'Hettie', 'Hetty', 'Nettie', 'Netty'),
    ('Henry', 'Harry', 'Hank'),
    ('Herbert', 'Herb', 'Bert', 'Bertie'),
    ('Herman', 'Manny', 'Mannie'),
    ('Hester', 'Essie', 'Ettie', 'Etty', 'Hettie', 'Hetty'),
    ('Hilary', 'Hill', 'Hillie'),
    ('Hilda', 'Hildie'),
    ('Hillary', 'Hill', 'Hillie'),
    ('Howard', 'Howie'),
    ('Hubert', 'Hugh', 'Bert', 'Bertie'),
    ('Hugh', 'Hughie', 'Hugo'),
    ('Hylda', 'Hildie'),
    ('Immanuel', 'Manny', 'Mannie', 'Manny', 'Mannie', 'Manny', 'Mannie'),
    ('Imogen', 'Immy', 'Immie'),
    ('Imogene', 'Immy', 'Immie'),
    ('Irene', 'Renie', 'Rena'),
    ('Irvin', 'Erv', 'Vin', 'Win'),
    ('Irvine', 'Erv', 'Vin', 'Win'),
    ('Irving', 'Erv', 'Vin', 'Win'),
    ('Irwin', 'Erv', 'Vin', 'Win'),
    ('Isaac', 'Ike'),
    ('Isaak', 'Ike'),
    ('Isabel', 'Bel', 'Bell', 'Belle', 'Bella', 'Issy'),
    ('Isabella', 'Bel', 'Bell', 'Belle', 'Bella', 'Issy'),
    ('Isabelle', 'Bel', 'Bell', 'Belle', 'Bella', 'Issy'),
    ('Isador', 'Izzy'),
    ('Isadore', 'Izzy'),
    ('Isidor', 'Izzy'),
    ('Isidore', 'Izzy'),
    ('Jack', 'Jackie', 'Jacky'),
    ('Jacob', 'Jake'),
    ('Jacqueline', 'Jackie', 'Jacky'),
    ('Jacquelyn', 'Jackie', 'Jacky'),
    ('James', 'Jim', 'Jimmy', 'Jimmie', 'Jamie', 'Jem'),
    ('Jane', 'Janie', 'Janey', 'Jenny', 'Jennie', 'Jen', 'Janet'),
    ('Janet', 'Jan', 'Nettie', 'Netty', 'Netta'),
    ('Janetta', 'Jan', 'Nettie', 'Netty', 'Netta'),
    ('Janette', 'Jan', 'Nettie', 'Netty', 'Netta'),
    ('Janice', 'Jan'),
    ('Janis', 'Jan'),
    ('Jason', 'Jay'),
    ('Jasper', 'Jay'),
    ('Jean', 'Jeanie', 'Jeannie'),
    ('Jeanette', 'Jeanie', 'Jeannie', 'Nettie', 'Netty', 'Netta'),
    ('Jeanne', 'Jeanie', 'Jeannie'),
    ('Jeannetta', 'Jeanie', 'Jeannie', 'Nettie', 'Netty', 'Netta'),
    ('Jeannette', 'Jeanie', 'Jeannie', 'Nettie', 'Netty', 'Netta'),
    ('Jeffery', 'Jeff'),
    ('Jeffrey', 'Jeff', 'Jeff', 'Jeff'),
    ('Jemima', 'Jem', 'Jemma', 'Mima', 'Mimi'),
    ('Jenice', 'Jan'),
    ('Jennifer', 'Jen', 'Jenny', 'Jennie', 'Jenne'),
    ('Jeremiah', 'Jerry'),
    ('Jeremy', 'Jerry'),
    ('Jerome', 'Jerry'),
    ('Jesse', 'Jess', 'Jessie', 'Jessy'),
    ('Jessica', 'Jess', 'Jessie'),
    ('Jillian', 'Jill'),
    ('Joan', 'Jo', 'Jody'),
    ('Joann', 'Jo', 'Jody'),
    ('Joanna', 'Jo', 'Jody'),
    ('Joanne', 'Jo', 'Jody'),
    ('Joceline', 'Jo', 'Lynn'),
    ('Jocelyn', 'Jo', 'Lynn'),
    ('Johanna', 'Jo', 'Jody'),
    ('John', 'Jack', 'Jackie', 'Jacky', 'Johnny'),
    ('Jonathan', 'Jon', 'Jonny'),
    ('Joseph', 'Joe', 'Joey', 'Jo', 'Jos', 'Jody'),
    ('Josephine', 'Jo', 'Josie', 'Josey', 'Jozy', 'Jody'),
    ('Joshua', 'Josh'),
    ('Joyce', 'Joy'),
    ('Judith', 'Judy', 'Judie', 'Jude', 'Jody', 'Jodie'),
    ('Julia', 'Julie', 'Jule'),
    ('Julian', 'Jule', 'Jules'),
    ('Juliana', 'Julie', 'Jule'),
    ('Julianne', 'Julie', 'Jule'),
    ('Juliet', 'Julie', 'Jule'),
    ('Juliette', 'Julie', 'Jule'),
    ('Julius', 'Jule', 'Jules'),
    ('Karen', 'Kari', 'Karrie'),
    ('Karin', 'Kari', 'Karrie'),
    ('Karol', 'Carrie', 'Carry'),
    ('Karoline', 'Carrie', 'Carry', 'Caddie', 'Caddy', 'Carlie', 'Carly', 'Callie', 'Cally', 'Carol', 'Lynn', 'Lynne', 'Lin'),
    ('Karyn', 'Kari', 'Karrie'),
    ('Katharine', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Katherine', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Kathleen', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Katty', 'Kattie'),
    ('Kathlene', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Katty', 'Kattie'),
    ('Kathlyn', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Katty', 'Kattie'),
    ('Kathlynne', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Katty', 'Kattie'),
    ('Kathrine', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Kathryn', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Kathrynne', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Katrina', 'Kate', 'Kathie', 'Kathy', 'Katie', 'Katy', 'Kay', 'Katty', 'Kattie', 'Kit', 'Kitty', 'Kittie'),
    ('Kelvin', 'Kel', 'Kelly'),
    ('Kendall', 'Ken', 'Kenny'),
    ('Kendrick', 'Ken', 'Kenny', 'Rick', 'Ricky'),
    ('Kenneth', 'Ken', 'Kenny'),
    ('Kent', 'Ken', 'Kenny'),
    ('Kevin', 'Kev'),
    ('Kimberley', 'Kim'),
    ('Kimberly', 'Kim'),
    ('Kristen', 'Kris', 'Kristi', 'Kristy', 'Kristie', 'Krista'),
    ('Kristin', 'Kris', 'Kristi', 'Kristy', 'Kristie', 'Krista'),
    ('Kristina', 'Kris', 'Kristi', 'Kristy', 'Kristie', 'Krista'),
    ('Kristine', 'Kris', 'Kristi', 'Kristy', 'Kristie', 'Krista'),
    ('Kristofer', 'Chris', 'Kris', 'Cris', 'Christy', 'Kit', 'Kester', 'Kristof', 'Toph', 'Topher', 'Kris', 'Kit', 'Kester'),
    ('Kristopher', 'Chris', 'Kris', 'Cris', 'Christy', 'Kit', 'Kester', 'Kristof', 'Toph', 'Topher', 'Kris', 'Kit', 'Kester'),
    ('Kurtis', 'Curt', 'Kurt', 'Kurt', 'Curt', 'Kurt', 'Curt'),
    ('Lamont', 'Monty', 'Monte'),
    ('Lancelot', 'Lance'),
    ('Launcelot', 'Lance'),
    ('Laura', 'Laurie', 'Lauri', 'Lolly'),
    ('Laureen', 'Laurie'),
    ('Laurel', 'Laurie'),
    ('Lauren', 'Laurie'),
    ('Laurena', 'Laurie'),
    ('Laurence', 'Larry', 'Lars', 'Laurie', 'Lawrie'),
    ('Laurene', 'Laurie'),
    ('Laurinda', 'Lori', 'Lorie', 'Lorrie', 'Laurie'),
    ('Laurine', 'Laurie'),
    ('Laverna', 'Verna'),
    ('Laverne', 'Verna'),
    ('Lavinia', 'Vina', 'Vinnie'),
    ('Lawrence', 'Larry', 'Lars', 'Laurie', 'Lawrie'),
    ('Lenora', 'Nora'),
    ('Lenore', 'Nora'),
    ('Leo', 'Lee'),
    ('Leon', 'Lee'),
    ('Leona', 'Lee'),
    ('Leonard', 'Leo', 'Leon', 'Len', 'Lenny', 'Lennie'),
    ('Leonora', 'Nora'),
    ('Leonore', 'Nora'),
    ('Leopold', 'Leo', 'Poldie'),
    ('Leroy', 'Lee', 'Roy'),
    ('Lesley', 'Les'),
    ('Leslie', 'Les'),
    ('Lester', 'Les'),
    ('Leticia', 'Lettie', 'Tisha'),
    ('Letitia', 'Lettie', 'Tisha'),
    ('Lewis', 'Lew', 'Lewie'),
    ('Lili', 'Lil', 'Lillie'),
    ('Lilian', 'Lily', 'Lilly', 'Lili', 'Lilli', 'Lil', 'Lillie'),
    ('Lilli', 'Lil', 'Lillie'),
    ('Lillian', 'Lily', 'Lilly', 'Lili', 'Lilli', 'Lil', 'Lillie'),
    ('Lilly', 'Lil', 'Lillie'),
    ('Lily', 'Lil', 'Lillie'),
    ('Lincoln', 'Lin', 'Linc', 'Lynn'),
    ('Linda', 'Lindy', 'Lin', 'Lynn', 'Lynne'),
    ('Lionel', 'Leo', 'Leon'),
    ('Lloyd', 'Loy', 'Floy'),
    ('Lora', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Loraine', 'Lora', 'Lori', 'Lorie', 'Lorrie'),
    ('Loreen', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Loren', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Lorena', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Lorence', 'Larry', 'Lars', 'Laurie', 'Lawrie'),
    ('Lorene', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Lorenzo', 'Larry', 'Lars', 'Laurie', 'Lawrie'),
    ('Loretta', 'Lori', 'Lorrie', 'Etta', 'Retta'),
    ('Lorette', 'Lori', 'Lorrie', 'Etta', 'Retta'),
    ('Lorinda', 'Lori', 'Lorie', 'Lorrie', 'Laurie'),
    ('Lorine', 'Lori', 'Lorie', 'Lorri', 'Lorrie'),
    ('Lorrain', 'Lora', 'Lori', 'Lorie', 'Lorrie'),
    ('Lorraine', 'Lora', 'Lori', 'Lorie', 'Lorrie'),
    ('Louis', 'Lou', 'Louie'),
    ('Louisa', 'Lou', 'Lu', 'Lulu', 'Lula', 'Lois'),
    ('Louise', 'Lou', 'Lu', 'Lulu', 'Lula', 'Lois'),
    ('Loyd', 'Loy', 'Floy'),
    ('Loyde', 'Loy', 'Floy'),
    ('Lucas', 'Luke'),
    ('Luci', 'Lu', 'Lulu', 'Luce', 'Lucky'),
    ('Lucia', 'Lu', 'Lulu', 'Luce', 'Lucky'),
    ('Lucie', 'Lu', 'Lulu', 'Luce', 'Lucky'),
    ('Lucile', 'Lu', 'Lucy', 'Lucky'),
    ('Lucille', 'Lu', 'Lucy', 'Lucky'),
    ('Lucinda', 'Lu', 'Lucy', 'Lucky', 'Cindy'),
    ('Lucy', 'Lu', 'Lulu', 'Luce', 'Lucky'),
    ('Luis', 'Lou', 'Louie'),
    ('Luke', 'Luke'),
    ('Lydia', 'Liddy', 'Lyddie'),
    ('Lynda', 'Lindy', 'Lin', 'Lynn', 'Lynne'),
    ('Mabel', 'Mab', 'Mabs', 'Mabbie'),
    ('Mabelle', 'Mab', 'Mabs', 'Mabbie'),
    ('Mable', 'Mab', 'Mabs', 'Mabbie'),
    ('Madeleine', 'Maddie', 'Maddy', 'Mady'),
    ('Madeline', 'Maddie', 'Maddy', 'Mady'),
    ('Madelyn', 'Maddie', 'Maddy', 'Mady'),
    ('Magdalen', 'Magda', 'Magsie', 'Lena'),
    ('Magdalena', 'Magda', 'Magsie', 'Lena'),
    ('Magdaline', 'Magda', 'Magsie', 'Lena'),
    ('Malcolm', 'Mal', 'Malc', 'Mac'),
    ('Manuel', 'Manny', 'Mannie', 'Manny', 'Mannie', 'Manny', 'Mannie'),
    ('Marc', 'Mark', 'Marc'),
    ('Marcia', 'Marcie', 'Marcy', 'Marci'),
    ('Marcus', 'Mark', 'Marc'),
    ('Margaret', 'Maggie', 'Marge', 'Margie', 'Marjorie', 'Margery', 'Madge', 'Margot', 'Margo', 'Magsie', 'Maisie', 'Daisy', 'Mamie', 'Maidie', 'Mae', 'May', 'Meg', 'Megan', 'Peggy', 'Greta', 'Gretchen', 'Rita'),
    ('Margarita', 'Maggie', 'Marge', 'Margie', 'Marjorie', 'Margery', 'Madge', 'Margot', 'Margo', 'Magsie', 'Maisie', 'Daisy', 'Mamie', 'Maidie', 'Mae', 'May', 'Meg', 'Megan', 'Peggy', 'Greta', 'Gretchen', 'Rita'),
    ('Margery', 'Marge', 'Margie'),
    ('Margret', 'Maggie', 'Marge', 'Margie', 'Marjorie', 'Margery', 'Madge', 'Margot', 'Margo', 'Magsie', 'Maisie', 'Daisy', 'Mamie', 'Maidie', 'Mae', 'May', 'Meg', 'Megan', 'Peggy', 'Greta', 'Gretchen', 'Rita'),
    ('Marguerite', 'Maggie', 'Marge', 'Margie', 'Marjorie', 'Margery', 'Madge', 'Margot', 'Margo', 'Magsie', 'Maisie', 'Daisy', 'Mamie', 'Maidie', 'Mae', 'May', 'Meg', 'Megan', 'Peggy', 'Greta', 'Gretchen', 'Rita'),
    ('Marian', 'Mary', 'Ann'),
    ('Marianna', 'Mary', 'Ann'),
    ('Marianne', 'Mary', 'Ann'),
    ('Maribel', 'Mary', 'Bell'),
    ('Maribelle', 'Mary', 'Bell'),
    ('Mariett', 'Mary', 'Etta', 'Ettie', 'Etty'),
    ('Marietta', 'Mary', 'Etta', 'Ettie', 'Etty'),
    ('Mariette', 'Mary', 'Etta', 'Ettie', 'Etty'),
    ('Marilyn', 'Mary', 'Lynn'),
    ('Marilynn', 'Mary', 'Lynn'),
    ('Marjorie', 'Marge', 'Margie'),
    ('Marjory', 'Marge', 'Margie'),
    ('Mark', 'Mark', 'Marc'),
    ('Markus', 'Mark', 'Marc'),
    ('Marlene', 'Mary', 'Lynn'),
    ('Marlyn', 'Mary', 'Lynn'),
    ('Marta', 'Marty', 'Mat', 'Mattie', 'Matty', 'Pat', 'Pattie', 'Patty'),
    ('Martha', 'Marty', 'Mat', 'Mattie', 'Matty', 'Pat', 'Pattie', 'Patty'),
    ('Martin', 'Mart', 'Marty'),
    ('Marvin', 'Marv', 'Merv'),
    ('Mary', 'Mae', 'May', 'Moll', 'Molly', 'Mollie', 'Polly', 'Mamie', 'Mimi', 'Minnie'),
    ('Maryann', 'Mary', 'Ann'),
    ('Maryanne', 'Mary', 'Ann'),
    ('Marylin', 'Mary', 'Lynn'),
    ('Mathilda', 'Mat', 'Matty', 'Mattie', 'Maud', 'Maude', 'Patty', 'Pattie', 'Tilda', 'Tillie', 'Tilly'),
    ('Matilda', 'Mat', 'Matty', 'Mattie', 'Maud', 'Maude', 'Patty', 'Pattie', 'Tilda', 'Tillie', 'Tilly'),
    ('Matthew', 'Matt', 'Mat', 'Matty', 'Mattie'),
    ('Maud', 'Maudie', 'Maudy'),
    ('Maude', 'Maudie', 'Maudy'),
    ('Maureen', 'Maury'),
    ('Maurice', 'Morry'),
    ('Maximilian', 'Max'),
    ('Maxine', 'Max', 'Maxie'),
    ('Megan', 'Meg'),
    ('Melanie', 'Mel', 'Mellie'),
    ('Melicent', 'Millie', 'Milly'),
    ('Melinda', 'Mel', 'Mellie', 'Linda', 'Mindy'),
    ('Melissa', 'Mel', 'Mellie', 'Missie', 'Missy', 'Lisa', 'Lissa'),
    ('Melvin', 'Mel'),
    ('Mercedes', 'Mercy', 'Sadie'),
    ('Meredith', 'Merry'),
    ('Mervin', 'Marv', 'Merv'),
    ('Michael', 'Mike', 'Mickey'),
    ('Michele', 'Mickey', 'Shelly'),
    ('Michelle', 'Mickey', 'Shelly'),
    ('Mildred', 'Millie', 'Milly'),
    ('Milicent', 'Millie', 'Milly'),
    ('Millicent', 'Millie', 'Milly'),
    ('Milton', 'Milt'),
    ('Miranda', 'Randy'),
    ('Mitchell', 'Mitch'),
    ('Mollie', 'Moll', 'Polly'),
    ('Molly', 'Moll', 'Polly'),
    ('Monica', 'Nicki'),
    ('Montague', 'Monty', 'Monte'),
    ('Montgomery', 'Monty', 'Monte'),
    ('Morris', 'Morry'),
    ('Mortimer', 'Mort', 'Morty'),
    ('Moses', 'Mo', 'Moe', 'Mose', 'Moss'),
    ('Nadine', 'Nada', 'Dee'),
    ('Natalia', 'Nattie', 'Natty'),
    ('Natalie', 'Nattie', 'Natty'),
    ('Natasha', 'Nattie', 'Natty'),
    ('Nathalie', 'Nattie', 'Natty'),
    ('Nathan', 'Nat', 'Nate'),
    ('Nathaniel', 'Nat', 'Nate'),
    ('Nell', 'Nellie', 'Nelly'),
    ('Nelle', 'Nellie', 'Nelly'),
    ('Nicholas', 'Nick', 'Nicky', 'Nicol', 'Cole'),
    ('Nicolas', 'Nick', 'Nicky', 'Nicol', 'Cole'),
    ('Nicole', 'Nicky', 'Nicki', 'Nikki', 'Nikky'),
    ('Norbert', 'Bert', 'Norby'),
    ('Norma', 'Normie'),
    ('Norman', 'Norm'),
    ('Octavia', 'Tave', 'Tavy', 'Tavia'),
    ('Olive', 'Ollie', 'Olly', 'Nollie', 'Livvy', 'Livia'),
    ('Oliver', 'Ollie', 'Noll', 'Nollie', 'Nolly'),
    ('Olivia', 'Ollie', 'Olly', 'Nollie', 'Livvy', 'Livia'),
    ('Oscar', 'Ossy'),
    ('Oswald', 'Ossy', 'Ozzie', 'Ozzy'),
    ('Oswold', 'Ossy', 'Ozzie', 'Ozzy'),
    ('Pamela', 'Pam', 'Pammie', 'Pammy'),
    ('Patricia', 'Pat', 'Patty', 'Patti', 'Pattie', 'Patsy', 'Tricia', 'Trisha', 'Trish', 'Trissie'),
    ('Patrick', 'Pat', 'Paddy', 'Patsy'),
    ('Paul', 'Pauly'),
    ('Paula', 'Paulie'),
    ('Paulina', 'Paulie'),
    ('Pauline', 'Paulie'),
    ('Pearl', 'Pearlie'),
    ('Peggy', 'Peg'),
    ('Penelope', 'Pen', 'Penny'),
    ('Peter', 'Pete'),
    ('Phebe', 'Pheb'),
    ('Philip', 'Phil', 'Pip'),
    ('Phillip', 'Phil', 'Pip'),
    ('Phoebe', 'Pheb'),
    ('Phyllis', 'Phyl', 'Phyllie', 'Phil'),
    ('Priscilla', 'Prissy'),
    ('Prudence', 'Prudie', 'Prudy', 'Prue', 'Pru'),
    ('Quentin', 'Quinn'),
    ('Quenton', 'Quinn'),
    ('Quincy', 'Quinn'),
    ('Quintin', 'Quinn'),
    ('Quinton', 'Quinn'),
    ('Rachel', 'Rachie', 'Rae', 'Ray'),
    ('Rafael', 'Raff', 'Rafe'),
    ('Ralph', 'Rafe'),
    ('Randal', 'Rand', 'Randy'),
    ('Randall', 'Rand', 'Randy'),
    ('Randolph', 'Rand', 'Randy', 'Dolph'),
    ('Raphael', 'Raff', 'Rafe'),
    ('Raquel', 'Kelly', 'Kellie'),
    ('Raymond', 'Ray'),
    ('Raymund', 'Ray'),
    ('Rebecca', 'Beck', 'Becky', 'Reba'),
    ('Regina', 'Reggie', 'Ray', 'Gina', 'Ginny', 'Rena'),
    ('Reginald', 'Reg', 'Reggie', 'Rex'),
    ('Renata', 'Nata', 'Natie', 'Rennie', 'Renny', 'Renae'),
    ('Reuben', 'Rube', 'Ruby'),
    ('Reynold', 'Ray'),
    ('Rhoda', 'Rodie'),
    ('Richard', 'Dick', 'Rick', 'Ricky', 'Rich', 'Richie'),
    ('Robert', 'Bob', 'Bobbie', 'Bobby', 'Dob', 'Rob', 'Robbie', 'Robby', 'Robin', 'Bert'),
    ('Roberta', 'Robbie', 'Robby', 'Robin', 'Robyn', 'Bobbie', 'Bobby', 'Berta', 'Bertie'),
    ('Roderic', 'Rod', 'Roddy', 'Rick', 'Ricky'),
    ('Roderick', 'Rod', 'Roddy', 'Rick', 'Ricky'),
    ('Rodger', 'Rod', 'Roddy', 'Rodge', 'Roge'),
    ('Rodney', 'Rod', 'Roddy'),
    ('Roger', 'Rod', 'Roddy', 'Rodge', 'Roge'),
    ('Roland', 'Rolly', 'Roly'),
    ('Ronald', 'Ron', 'Ronnie', 'Ronny'),
    ('Rosa', 'Rosie', 'Rosy'),
    ('Rosabel', 'Rose', 'Rosie', 'Rosy', 'Bell'),
    ('Rosabella', 'Rose', 'Rosie', 'Rosy', 'Bell'),
    ('Rosabelle', 'Rose', 'Rosie', 'Rosy', 'Bell'),
    ('Rosalee', 'Rose', 'Rosie', 'Rosy'),
    ('Rosalie', 'Rose', 'Rosie', 'Rosy'),
    ('Rosalind', 'Rose', 'Rosie', 'Rosy', 'Linda'),
    ('Rosalinda', 'Rose', 'Rosie', 'Rosy', 'Linda'),
    ('Rosaline', 'Rose', 'Rosie', 'Rosy'),
    ('Rosalyn', 'Rose', 'Rosie', 'Rosy'),
    ('Rosanna', 'Rose', 'Rosie', 'Rosy'),
    ('Rosanne', 'Rose', 'Rosie', 'Rosy'),
    ('Roscoe', 'Ross'),
    ('Rose', 'Rosie', 'Rosy'),
    ('Roseanna', 'Rose', 'Rosie', 'Rosy'),
    ('Rosemarie', 'Rose', 'Rosie', 'Rosy'),
    ('Rosemary', 'Rose', 'Rosie', 'Rosy'),
    ('Roxana', 'Roxie', 'Roxy'),
    ('Roxanna', 'Roxie', 'Roxy'),
    ('Roxanne', 'Roxie', 'Roxy'),
    ('Ruben', 'Rube', 'Ruby'),
    ('Rubin', 'Rube', 'Ruby'),
    ('Rubina', 'Ruby', 'Rubie'),
    ('Ruby', 'Ruby', 'Rubie'),
    ('Rudolf', 'Rudy', 'Rolf', 'Rolph', 'Dolph', 'Dolf'),
    ('Rudolph', 'Rudy', 'Rolf', 'Rolph', 'Dolph', 'Dolf'),
    ('Russel', 'Russ'),
    ('Russell', 'Russ'),
    ('Ruth', 'Ruthie'),
    ('Sabrina', 'Brina', 'Sabby'),
    ('Samantha', 'Sam', 'Sammie', 'Sammy'),
    ('Sampson', 'Sam', 'Sammy'),
    ('Samson', 'Sam', 'Sammy'),
    ('Samuel', 'Sam', 'Sammy'),
    ('Sara', 'Sal', 'Sally', 'Sallie', 'Sadie'),
    ('Sarah', 'Sal', 'Sally', 'Sallie', 'Sadie'),
    ('Scott', 'Scotty'),
    ('Sebastian', 'Seb', 'Bass'),
    ('Selena', 'Lena', 'Lina'),
    ('Selene', 'Lena', 'Lina'),
    ('Selina', 'Lena', 'Lina'),
    ('Seymour', 'Sy'),
    ('Sheldon', 'Shelly', 'Don'),
    ('Shirlee', 'Shirl'),
    ('Shirley', 'Shirl'),
    ('Shirlie', 'Shirl'),
    ('Sibyl', 'Sib', 'Sibbie'),
    ('Sibylle', 'Sib', 'Sibbie'),
    ('Sidney', 'Sid', 'Syd'),
    ('Silvester', 'Syl', 'Vester'),
    ('Silvia', 'Syl', 'Sylvie'),
    ('Simeon', 'Si', 'Sim', 'Simie', 'Simmy'),
    ('Simon', 'Si', 'Sim', 'Simie', 'Simmy'),
    ('Solomon', 'Sol', 'Solly', 'Sal'),
    ('Sophia', 'Sophie', 'Sophy'),
    ('Stanley', 'Stan'),
    ('Stefan', 'Steve', 'Stevie', 'Steph', 'Steff', 'Stef'),
    ('Stefana', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stefania', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stefanie', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Steffan', 'Steve', 'Stevie', 'Steph', 'Steff', 'Stef'),
    ('Steffanie', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stephan', 'Steve', 'Stevie', 'Steph', 'Steff', 'Stef'),
    ('Stephana', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stephania', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stephanie', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stephany', 'Steph', 'Stephie', 'Steff', 'Steffy', 'Stevie'),
    ('Stephen', 'Steve', 'Stevie', 'Steph', 'Steff', 'Stef'),
    ('Steven', 'Steve', 'Stevie', 'Steph', 'Steff', 'Stef'),
    ('Stewart', 'Stu', 'Stew'),
    ('Stuart', 'Stu', 'Stew'),
    ('Susan', 'Sue', 'Susie', 'Susi', 'Susy', 'Suzie', 'Suzy', 'Sukie'),
    ('Susanna', 'Sue', 'Susie', 'Susi', 'Susy', 'Suzie', 'Suzy', 'Sukie'),
    ('Susannah', 'Sue', 'Susie', 'Susi', 'Susy', 'Suzie', 'Suzy', 'Sukie'),
    ('Susanne', 'Sue', 'Susie', 'Susi', 'Susy', 'Suzie', 'Suzy', 'Sukie'),
    ('Suzanne', 'Sue', 'Susie', 'Susi', 'Susy', 'Suzie', 'Suzy', 'Sukie'),
    ('Sybil', 'Sib', 'Sibbie'),
    ('Syble', 'Sib', 'Sibbie'),
    ('Sydney', 'Sid', 'Syd'),
    ('Sylvester', 'Syl', 'Vester'),
    ('Sylvia', 'Syl', 'Sylvie'),
    ('Tabitha', 'Tabby'),
    ('Tamar', 'Tammy', 'Tammie'),
    ('Tamara', 'Tammy', 'Tammie'),
    ('Terence', 'Terry'),
    ('Teresa', 'Terry', 'Terri', 'Teri', 'Terrie', 'Tess', 'Tessa', 'Tessie', 'Tracy', 'Trissie'),
    ('Terrance', 'Terry'),
    ('Terrence', 'Terry'),
    ('Thaddeus', 'Thad', 'Tad'),
    ('Thadeus', 'Thad', 'Tad'),
    ('Theodora', 'Dora', 'Theo'),
    ('Theodore', 'Ted', 'Teddy', 'Theo'),
    ('Theresa', 'Terry', 'Terri', 'Teri', 'Terrie', 'Tess', 'Tessa', 'Tessie', 'Tracy', 'Trissie'),
    ('Therese', 'Terry', 'Terri', 'Teri', 'Terrie', 'Tess', 'Tessa', 'Tessie', 'Tracy', 'Trissie'),
    ('Thomas', 'Tom', 'Tommy'),
    ('Tiffany', 'Tiff', 'Tiffy'),
    ('Timothy', 'Tim', 'Timmy'),
    ('Tobias', 'Toby', 'Tobi', 'Tobie'),
    ('Tyler', 'Ty'),
    ('Ursula', 'Ursa', 'Ursie', 'Sulie'),
    ('Valentina', 'Val', 'Vallie'),
    ('Valentine', 'Val'),
    ('Valeria', 'Val', 'Vallie'),
    ('Valerie', 'Val', 'Vallie'),
    ('Valery', 'Val', 'Vallie'),
    ('Vanessa', 'Van', 'Vannie', 'Nessa'),
    ('Vergil', 'Virge'),
    ('Vernon', 'Vern'),
    ('Veronica', 'Nicky', 'Nicki', 'Ronnie', 'Ronni', 'Ronny'),
    ('Victor', 'Vic', 'Vick'),
    ('Victoria', 'Vic', 'Vick', 'Vickie', 'Vicky', 'Vicki', 'Viki', 'Vikki'),
    ('Vincent', 'Vince', 'Vin', 'Vinny'),
    ('Viola', 'Vi'),
    ('Violet', 'Vi', 'Lettie'),
    ('Violetta', 'Vi', 'Lettie'),
    ('Violette', 'Vi', 'Lettie'),
    ('Virgil', 'Virge'),
    ('Virginia', 'Ginger', 'Ginny', 'Jinny', 'Jenny', 'Virgie'),
    ('Vivian', 'Viv'),
    ('Vivien', 'Viv'),
    ('Wallace', 'Wally'),
    ('Walter', 'Walt', 'Wally'),
    ('Wesley', 'Wes'),
    ('Wilber', 'Will', 'Willie', 'Willy'),
    ('Wilbur', 'Will', 'Willie', 'Willy'),
    ('Wiley', 'Will', 'Willie', 'Willy'),
    ('Wilfred', 'Will', 'Willie', 'Willy', 'Fred', 'Freddie', 'Freddy'),
    ('Wilfrid', 'Will', 'Willie', 'Willy', 'Fred', 'Freddie', 'Freddy'),
    ('Wilhelmina', 'Willa', 'Wilma', 'Willie', 'Billie', 'Mina', 'Minnie'),
    ('Willard', 'Will', 'Willie', 'Willy'),
    ('William', 'Bill', 'Billy', 'Billie', 'Will', 'Willie', 'Willy'),
    ('Willis', 'Bill', 'Billy', 'Billie', 'Will', 'Willie', 'Willy'),
    ('Wilson', 'Will', 'Willie', 'Willy'),
    ('Winfred', 'Win', 'Winnie', 'Winny', 'Fred', 'Freddie', 'Freddy'),
    ('Winifred', 'Winnie', 'Freda', 'Freddie'),
    ('Winston', 'Win', 'Winnie', 'Winny'),
    ('Woodrow', 'Wood', 'Woody'),
    ('Yvette', 'Vettie', 'Vetta'),
    ('Yvonne', 'Vonnie', 'Vonna'),
    ('Zachariah', 'Zack', 'Zacky', 'Zach'),
    ('Zacharias', 'Zack', 'Zacky', 'Zach'),
    ('Zachary', 'Zack', 'Zacky', 'Zach'),
    ('Zoe', 'Zoey'),
)